### ISSUE TITLE
how to run server app

### ISSUE THREAD

**Issue by marcoaros** [LiteKite/Android-AIDL#1]
hi,
After install server app, I don't know how to run it.I try to run it from common line
I use "adb shell am startservice -n  com.litekite.server/.service.BankService", but I get this error
Error: Requires permission com.litekite.server.permission.BIND_BANK_SERVICE

btw, my phone is android 10
thank you very much!

**Comment by svignesh93** [comment]
Hi @marcoaros ,

The permission "com.litekite.server.permission.BIND_BANK_SERVICE" is a signature level permission and this service can only be started or bound with the application that is signed with the same keystore credentials.

Please install client app also to make a service connection. Internally, the service was started in ConnectorLib library.
